-- loc/de.lua — German. Machine translated (game-anchored terms); corrections
-- welcome. Keys omitted here fall back to English.
local require = ...

return {
    TYPES = {
        BUTTON   = "Schaltfläche",
        SLIDER   = "Schieberegler",
        CYCLE    = "Schieberegler",
        CHECKBOX = "Kontrollkästchen",
        TAB      = "Registerkarte",
        CARD     = "Karte",
        JOKER    = "Joker",
        TAROT    = "Tarot",
        PLANET   = "Planet",
        SPECTRAL = "Spektral",
        VOUCHER  = "Gutschein",
        BOOSTER  = "Booster-Paket",
        TEXT_FIELD = "Textfeld",
    },
    STATUS = { ON = "an", OFF = "aus" },
    LABELS = { LOCKED = "gesperrt", EMPTY = "leer", NOT_DISCOVERED = "Nicht entdeckt" },

    KEYS = {
        RETURN = "Eingabe", KPENTER = "Eingabe (Ziffernblock)",
        LSHIFT = "Umschalt links", RSHIFT = "Umschalt rechts",
        LCTRL = "Strg links", RCTRL = "Strg rechts",
        LALT = "Alt links", RALT = "Alt rechts",
        UP = "Hoch", DOWN = "Runter", LEFT = "Links", RIGHT = "Rechts",
        SPACE = "Leertaste", ESCAPE = "Escape", TAB = "Tab", BACKSPACE = "Rücktaste",
        CTRL = "Strg", SHIFT = "Umschalt", ALT = "Alt",
        UNBOUND = "(nicht belegt)",
    },

    PAD = {
        DPUP = "Steuerkreuz hoch", DPDOWN = "Steuerkreuz runter",
        DPLEFT = "Steuerkreuz links", DPRIGHT = "Steuerkreuz rechts",
        A = "A", B = "B", X = "X", Y = "Y",
        LEFTSHOULDER = "Linke Schultertaste", RIGHTSHOULDER = "Rechte Schultertaste",
        LEFTSTICK = "Linker Stick gedrückt", RIGHTSTICK = "Rechter Stick gedrückt",
        BACK = "Back", START = "Start", GUIDE = "Guide",
        TRIGGERLEFT = "Linker Trigger", TRIGGERRIGHT = "Rechter Trigger",
        CHORD = "{mod} + {button}",
    },

    MISC = {
        LOADED = "Blindfold geladen.",
    },
    RARITY = { COMMON = "gewöhnlicher", UNCOMMON = "ungewöhnlicher", RARE = "seltener", LEGENDARY = "legendärer" },
    POSITION = { OF = "{index} von {total}" },

    SCREEN = {
        PLAYING      = "Spiel",
        SHOP         = "Laden",
        BLIND_SELECT = "Blind-Auswahl",
        CASH_OUT     = "Auszahlung",
        PACK         = "Booster-Paket",
        GAME_OVER    = "Spiel vorbei",
        MAIN_MENU    = "Hauptmenü",
        MENU         = "Menü",
    },

    MENU = {
        DISCORD = "Discord",
        TWITTER = "Twitter",
        CONFIRM_UNLOCK = "Alles freischalten bestätigen",
        CONFIRM_ACTION = "{action} bestätigen",
        COMPLETED      = "abgeschlossen",
    },

    CONTAINER = {
        HAND        = "Hand",
        JOKERS      = "Joker",
        CONSUMABLES = "Verbrauchsgegenstände",
        VOUCHERS    = "Gutscheine",
        PACKS       = "Pakete",
        DECK        = "Deck",
        PLAYED      = "Gespielt",
        SHOP        = "Laden",
        SHOP_GOODS  = "Gutscheine und Pakete",
        PACK        = "Paket",
    },

    PACK = {
        CHOOSE    = "Wähle {choices} von {count}",
        CANT_SKIP = "Überspringen nicht möglich",
    },

    CARD = {
        PLAYING    = "{suit} {rank}",
        DEBUFFED   = "geschwächt",
        FACE_DOWN  = "verdeckt",
        TELL_SMALL    = "kleine Karte",
        TELL_SQUARE   = "quadratische Karte",
        TELL_RED_BACK = "rote Rückseite",
        SELL       = "Verkaufswert {amount}$",
        CANT_SELL  = "nicht verkäuflich",
        PINNED     = "angeheftet",
        FORCED     = "erzwungen",
        WIN_STICKER = "{stake}-Sticker",
        SELECTED   = "ausgewählt",
        DESELECTED = "abgewählt",
        TIP        = "{name}, {desc}",
    },
    EDITION = {
        foil = "Folie", holographic = "holografisch",
        polychrome = "polychrom", negative = "negativ",
    },
    SEAL = { GOLD = "Goldsiegel", RED = "rotes Siegel", BLUE = "blaues Siegel", PURPLE = "lila Siegel" },

    INPUT = {
        NAV_UP = "Nach oben", NAV_DOWN = "Nach unten",
        NAV_LEFT = "Nach links", NAV_RIGHT = "Nach rechts",
        ROW_START = "Zeilenanfang", ROW_END = "Zeilenende",
        SELECT = "Auswählen / Aktivieren", GRAB = "Aufnehmen / Ablegen",
        BACK = "Zurück / Abwählen", PAUSE = "Pause",
        PLAY_HAND = "Hand spielen", DISCARD = "Abwerfen",
        SELL = "Verkaufen", USE = "Verwenden",
        TAB_LEFT = "Vorherige Registerkarte", TAB_RIGHT = "Nächste Registerkarte",
        VIEW_DECK = "Deck ansehen",
        RUN_INFO = "Run-Info", DEBUG_DUMP = "Debug: Fokus ausgeben",
        BUFFER_NEXT_ITEM = "Puffer: Nächster Eintrag", BUFFER_PREV_ITEM = "Puffer: Vorheriger Eintrag",
        BUFFER_NEXT = "Puffer: Nächster Puffer", BUFFER_PREV = "Puffer: Vorheriger Puffer",
        INFO_HANDS = "Vorlesen: Verbleibende Hände", INFO_DISCARDS = "Vorlesen: Verbleibende Abwürfe",
        INFO_SCORE = "Vorlesen: Punkte und Ziel", INFO_JOKERS = "Vorlesen: Joker-Plätze",
        INFO_MONEY = "Vorlesen: Geld",
    },

    BUFFER = {
        GAME = "Spiel",
        CARD = "Karte",
        JOKER = "Joker",
        CONSUMABLE = "Verbrauchsgegenstand",
        CASHOUT = "Auszahlung",
        UI = "UI",
        NONE = "Keine Puffer",
        EMPTY = "Puffer {buffer} ist leer",
        CURRENT = "{buffer}, {item}",
    },
    GAME = {
        HANDS    = "{count} Hände übrig",
        DISCARDS = "{count} Abwürfe übrig",
        MONEY    = "{amount}$",
        SCORE    = "{score} von {req}",
        BLIND    = "Blind, {name}",
        ANTE     = "Ante, {ante} von 8",
        ROUND    = "Runde, {round}",
        JOKERS   = "{count} von {slots} Jokern",
        NOT_NOW  = "Zurzeit nicht verfügbar",
    },

    STATS = {
        USES = "{count} Verwendungen",
    },

    DECK_VIEW = {
        NAME_DESC = "{name}: {desc}",
        TALLY     = "{label}, {count}",
        TALLY_MOD = "{label}, Basis {base}, effektiv {effective}",
        DRAWN     = "gezogen",
        FLIPPED   = "{count} verdeckt gezogen",
    },

    BLIND = {
        REQUIREMENT = "mindestens {amount} Punkte",
        REWARD      = "Belohnung {dollars}$",
        SKIP        = "überspringen",
        NOT_CURRENT = "Nicht der aktuelle Blind",
        REROLL_USED = "In diesem Ante bereits neu gewürfelt",
    },

    PLAY = {
        PLAY_HAND   = "Hand spielen",
        DISCARD     = "Abwerfen",
        SORT_RANK   = "Nach Rang sortieren",
        SORT_SUIT   = "Nach Farbe sortieren",
        SORTED_RANK = "Nach Rang sortiert",
        SORTED_SUIT = "Nach Farbe sortiert",
        NO_CARDS    = "Keine Karten ausgewählt",
        NO_DISCARDS = "Keine Abwürfe übrig",
        CANT_SELECT = "Auswahl nicht möglich",
        PICKED_UP   = "Aufgenommen, {name}",
        PICKUP_CANCELLED = "Abgebrochen",
        MOVED       = "Verschoben",
        PINNED_CANT_MOVE = "Angeheftet, nicht verschiebbar",
        PLACE_LEFT    = "links von {name} ablegen",
        PLACE_BETWEEN = "zwischen {left} und {right} ablegen",
        PLACE_RIGHT   = "rechts von {name} ablegen",
        CANT_MOVE_HERE = "Hier nicht ablegbar",
        USED        = "Verwendet",
        CANT_USE    = "Zurzeit nicht verwendbar",
        NEEDS_TARGETS = "Erfordert ausgewählte Handkarten",
        SOLD        = "Verkauft",
        CANT_SELL   = "Nicht verkäuflich",
    },

    ROUND = {
        HAND_PLAYED = "Hand gespielt, {count} Hände übrig",
        DISCARDED   = "Abgeworfen, {count} Abwürfe übrig",
        HOOK_DISCARD   = "The Hook wirft {cards} ab",
        JOKER_DEBUFFED = "{name} geschwächt",
        OX    = "Geld auf 0$ gesetzt",
        TOOTH = "{amount}$ verloren",
    },

    SHOP = {
        COST = "{cost}$",
        FREE = "gratis",
        SELL = "Verkaufswert {cost}$",
        REROLL = "Neu würfeln, {cost}$",
        CANT_AFFORD = "Nicht genug Geld",
        NO_ROOM     = "Kein Platz",
        BOUGHT      = "Gekauft",
        BOUGHT_USED = "Gekauft und verwendet",
        REDEEMED    = "Eingelöst",
        EMPTY       = "leer",
    },

    CASHOUT = {
        LABEL         = "Auszahlung",
        TOTAL         = "{dollars}$",
        ROW           = "{label}, {dollars}$",
        BLIND_ROW     = "Blind-Belohnung, {dollars}$",
        SAVED         = "Von Mr. Bones gerettet",
        HANDS_ROW     = "Verbleibende Hände, {count}, {dollars}$",
        DISCARDS_ROW  = "Verbleibende Abwürfe, {count}, {dollars}$",
        INTEREST_ROW  = "Zinsen, {dollars}$, {rate} pro 5$ bis maximal {max}",
        JOKER         = "Joker",
        TAG           = "Tag",
    },

    SCORING = {
        HAND    = "{name}, {chips} Chips, {mult} Mult",
        HAND_LEVEL = "{name} aufgestiegen auf Stufe {level}, {chips} Chips, {mult} Mult",
        HAND_LEVEL_DOWN = "{name} gesunken auf Stufe {level}, {chips} Chips, {mult} Mult",
        CHIPS   = "{amt} Chips",
        MULT    = "plus {amt} Mult",
        XMULT   = "mal {amt} Mult",
        DOLLARS = "{amt}$",
        DEBUFF  = "{source} geschwächt",
        SOURCE  = "{source}, {effect}",
        TOTAL   = "{chips} Chips mal {mult} Mult ergibt {score}",
        SCORE   = "{score}",
    },

    SET = {
        SCORING_ENABLED = "Wertung ansagen",
        HAND_PREVIEW    = "Hand beim Auswählen ansagen",
        SCORING_DETAIL  = "Wertungsdetail",
        DETAIL_FULL     = "Vollständig",
        DETAIL_JOKERS   = "Nur Joker",
        DETAIL_SUMMARY  = "Zusammenfassung",
        ROUND_ACTIONS   = "Spielen und Abwerfen ansagen",
        KEYBINDS        = "Tastenbelegung",
        ANNOUNCEMENTS   = "Ansagen",
        TUTORIAL        = "Tutorial spielen",
        UNAVAILABLE     = "Blindfold-Einstellungen nicht verfügbar",
        PRESS_KEY       = "Taste oder Controller-Knopf für {action} drücken",
        BOUND           = "{action} belegt mit {key}",
        CANCELLED       = "Neubelegung abgebrochen",
        ANN_TYPE        = "Typ ansagen",
        ANN_SUBTYPE     = "Seltenheit ansagen",
        ANN_SELECTED    = "Auswahl ansagen",
        ANN_DESCRIPTION = "Beschreibungen ansagen",
        ANN_TOOLTIP     = "Tooltips ansagen",
        ANN_EXTRAS      = "Optionsinfo ansagen",
        ANN_POSITION    = "Position ansagen",
        ANN_CONTAINER   = "Bereich ansagen",
        ANN_SCREEN      = "Bildschirmwechsel ansagen",
    },
}
