-- loc/es_es.lua â€” Spanish (Spain). Machine translated (game-anchored terms);
-- corrections welcome. Keys omitted here fall back to English.
local require = ...

return {
    TYPES = {
        BUTTON   = "botÃ³n",
        SLIDER   = "control deslizante",
        CYCLE    = "control deslizante",
        CHECKBOX = "casilla",
        TAB      = "pestaÃ±a",
        CARD     = "carta",
        JOKER    = "comodÃ­n",
        TAROT    = "tarot",
        PLANET   = "planeta",
        SPECTRAL = "espectral",
        VOUCHER  = "vale",
        BOOSTER  = "paquete potenciador",
        TEXT_FIELD = "campo de texto",
    },
    STATUS = { ON = "activado", OFF = "desactivado" },
    LABELS = { LOCKED = "bloqueado", EMPTY = "vacÃ­o", NOT_DISCOVERED = "No descubierto" },

    KEYS = {
        RETURN = "Intro", KPENTER = "Intro (teclado numÃ©rico)",
        LSHIFT = "MayÃºs izquierda", RSHIFT = "MayÃºs derecha",
        LCTRL = "Ctrl izquierda", RCTRL = "Ctrl derecha",
        LALT = "Alt izquierda", RALT = "Alt derecha",
        UP = "Arriba", DOWN = "Abajo", LEFT = "Izquierda", RIGHT = "Derecha",
        SPACE = "Espacio", ESCAPE = "Escape", TAB = "Tabulador", BACKSPACE = "Retroceso",
        CTRL = "Ctrl", SHIFT = "MayÃºs", ALT = "Alt",
        UNBOUND = "(sin asignar)",
    },

    PAD = {
        DPUP = "Cruceta arriba", DPDOWN = "Cruceta abajo",
        DPLEFT = "Cruceta izquierda", DPRIGHT = "Cruceta derecha",
        A = "A", B = "B", X = "X", Y = "Y",
        LEFTSHOULDER = "BotÃ³n superior izquierdo", RIGHTSHOULDER = "BotÃ³n superior derecho",
        LEFTSTICK = "Clic de stick izquierdo", RIGHTSTICK = "Clic de stick derecho",
        BACK = "Back", START = "Start", GUIDE = "Guide",
        TRIGGERLEFT = "Gatillo izquierdo", TRIGGERRIGHT = "Gatillo derecho",
        CHORD = "{mod} + {button}",
    },

    MISC = {
        LOADED = "Blindfold cargado.",
    },
    RARITY = { COMMON = "comÃºn", UNCOMMON = "poco comÃºn", RARE = "raro", LEGENDARY = "legendario" },
    POSITION = { OF = "{index} de {total}" },

    SCREEN = {
        PLAYING      = "Partida",
        SHOP         = "Tienda",
        BLIND_SELECT = "SelecciÃ³n de ciega",
        CASH_OUT     = "Cobro",
        PACK         = "Paquete potenciador",
        GAME_OVER    = "Fin de la partida",
        MAIN_MENU    = "MenÃº principal",
        MENU         = "MenÃº",
    },

    MENU = {
        DISCORD = "Discord",
        TWITTER = "Twitter",
        CONFIRM_UNLOCK = "Confirmar desbloquear todo",
        CONFIRM_ACTION = "Confirmar {action}",
        COMPLETED      = "completado",
    },

    CONTAINER = {
        HAND        = "Mano",
        JOKERS      = "Comodines",
        CONSUMABLES = "Consumibles",
        VOUCHERS    = "Vales",
        PACKS       = "Paquetes",
        DECK        = "Baraja",
        PLAYED      = "Jugadas",
        SHOP        = "Tienda",
        SHOP_GOODS  = "Vales y paquetes",
        PACK        = "Paquete",
    },

    PACK = {
        CHOOSE    = "Elige {choices} de {count}",
        CANT_SKIP = "No se puede omitir",
    },

    CARD = {
        PLAYING    = "{rank} de {suit}",
        DEBUFFED   = "debilitada",
        FACE_DOWN  = "boca abajo",
        TELL_SMALL    = "carta pequeÃ±a",
        TELL_SQUARE   = "carta cuadrada",
        TELL_RED_BACK = "dorso rojo",
        SELL       = "venta {amount}$",
        CANT_SELL  = "no se puede vender",
        PINNED     = "fijado",
        FORCED     = "forzada",
        WIN_STICKER = "pegatina de {stake}",
        SELECTED   = "seleccionada",
        DESELECTED = "deseleccionada",
        TIP        = "{name}, {desc}",
    },
    EDITION = {
        foil = "laminada", holographic = "hologrÃ¡fica",
        polychrome = "policroma", negative = "negativa",
    },
    SEAL = { GOLD = "sello dorado", RED = "sello rojo", BLUE = "sello azul", PURPLE = "sello morado" },

    INPUT = {
        NAV_UP = "Navegar arriba", NAV_DOWN = "Navegar abajo",
        NAV_LEFT = "Navegar a la izquierda", NAV_RIGHT = "Navegar a la derecha",
        ROW_START = "Inicio de fila", ROW_END = "Fin de fila",
        SELECT = "Seleccionar / Activar", GRAB = "Tomar / Colocar",
        BACK = "AtrÃ¡s / Deseleccionar", PAUSE = "Pausa",
        PLAY_HAND = "Jugar mano", DISCARD = "Descartar",
        SELL = "Vender", USE = "Usar",
        TAB_LEFT = "PestaÃ±a anterior", TAB_RIGHT = "PestaÃ±a siguiente",
        VIEW_DECK = "Ver baraja",
        RUN_INFO = "InformaciÃ³n de la partida", DEBUG_DUMP = "Debug: volcar foco",
        BUFFER_NEXT_ITEM = "BÃºfer: elemento siguiente", BUFFER_PREV_ITEM = "BÃºfer: elemento anterior",
        BUFFER_NEXT = "BÃºfer: bÃºfer siguiente", BUFFER_PREV = "BÃºfer: bÃºfer anterior",
        INFO_HANDS = "Leer: manos restantes", INFO_DISCARDS = "Leer: descartes restantes",
        INFO_SCORE = "Leer: puntuaciÃ³n y objetivo", INFO_JOKERS = "Leer: huecos de comodÃ­n",
        INFO_MONEY = "Leer: dinero",
    },

    BUFFER = {
        GAME = "Partida",
        CARD = "Carta",
        JOKER = "ComodÃ­n",
        CONSUMABLE = "Consumible",
        CASHOUT = "Cobro",
        UI = "Interfaz",
        NONE = "Sin bÃºferes",
        EMPTY = "El bÃºfer {buffer} estÃ¡ vacÃ­o",
        CURRENT = "{buffer}, {item}",
    },
    GAME = {
        HANDS    = "{count} manos restantes",
        DISCARDS = "{count} descartes restantes",
        MONEY    = "{amount}$",
        SCORE    = "{score} de {req}",
        BLIND    = "Ciega, {name}",
        ANTE     = "Apuesta inicial, {ante} de 8",
        ROUND    = "Ronda, {round}",
        JOKERS   = "{count} de {slots} comodines",
        NOT_NOW  = "No disponible ahora",
    },

    STATS = {
        USES = "{count} usos",
    },

    DECK_VIEW = {
        NAME_DESC = "{name}: {desc}",
        TALLY     = "{label}, {count}",
        TALLY_MOD = "{label}, base {base}, efectivo {effective}",
        DRAWN     = "robada",
        FLIPPED   = "{count} robadas boca abajo",
    },

    BLIND = {
        REQUIREMENT = "consigue al menos {amount}",
        REWARD      = "recompensa {dollars}$",
        SKIP        = "omitir",
        NOT_CURRENT = "No es la ciega actual",
        REROLL_USED = "Ya se volvió a tirar en esta apuesta inicial",
    },

    PLAY = {
        PLAY_HAND   = "Jugar mano",
        DISCARD     = "Descartar",
        SORT_RANK   = "Ordenar por valor",
        SORT_SUIT   = "Ordenar por palo",
        SORTED_RANK = "Ordenado por valor",
        SORTED_SUIT = "Ordenado por palo",
        NO_CARDS    = "No hay cartas seleccionadas",
        NO_DISCARDS = "No quedan descartes",
        CANT_SELECT = "No se puede seleccionar",
        PICKED_UP   = "Tomada, {name}",
        PICKUP_CANCELLED = "Cancelado",
        MOVED       = "Movida",
        PINNED_CANT_MOVE = "Fijado, no se puede mover",
        PLACE_LEFT    = "colocar a la izquierda de {name}",
        PLACE_BETWEEN = "colocar entre {left} y {right}",
        PLACE_RIGHT   = "colocar a la derecha de {name}",
        CANT_MOVE_HERE = "No se puede colocar aquÃ­",
        USED        = "Usada",
        CANT_USE    = "No se puede usar ahora",
        NEEDS_TARGETS = "Requiere cartas seleccionadas en la mano",
        SOLD        = "Vendida",
        CANT_SELL   = "No se puede vender",
    },

    ROUND = {
        HAND_PLAYED = "Mano jugada, quedan {count} manos",
        DISCARDED   = "Descartado, quedan {count} descartes",
        HOOK_DISCARD   = "The Hook descarta {cards}",
        JOKER_DEBUFFED = "{name} debilitado",
        OX    = "Dinero puesto a 0$",
        TOOTH = "{amount}$ perdidos",
    },

    SHOP = {
        COST = "{cost}$",
        FREE = "gratis",
        SELL = "venta {cost}$",
        REROLL = "Volver a tirar, {cost}$",
        CANT_AFFORD = "No tienes suficiente dinero",
        NO_ROOM     = "No hay sitio",
        BOUGHT      = "Comprado",
        BOUGHT_USED = "Comprado y usado",
        REDEEMED    = "Canjeado",
        EMPTY       = "vacÃ­o",
    },

    CASHOUT = {
        LABEL         = "Cobrar",
        TOTAL         = "{dollars}$",
        ROW           = "{label}, {dollars}$",
        BLIND_ROW     = "Recompensa de ciega, {dollars}$",
        SAVED         = "Salvado por Mr. Bones",
        HANDS_ROW     = "Manos restantes, {count}, {dollars}$",
        DISCARDS_ROW  = "Descartes restantes, {count}, {dollars}$",
        INTEREST_ROW  = "Intereses, {dollars}$, {rate} por cada 5$ hasta {max}",
        JOKER         = "ComodÃ­n",
        TAG           = "Etiqueta",
    },

    SCORING = {
        HAND    = "{name}, {chips} fichas, {mult} multi",
        HAND_LEVEL = "{name} subiÃ³ al nivel {level}, {chips} fichas, {mult} multi",
        HAND_LEVEL_DOWN = "{name} bajÃ³ al nivel {level}, {chips} fichas, {mult} multi",
        CHIPS   = "{amt} fichas",
        MULT    = "mÃ¡s {amt} multi",
        XMULT   = "por {amt} multi",
        DOLLARS = "{amt}$",
        DEBUFF  = "{source} debilitado",
        SOURCE  = "{source}, {effect}",
        TOTAL   = "{chips} fichas por {mult} multi es igual a {score}",
        SCORE   = "{score}",
    },

    SET = {
        SCORING_ENABLED = "Anunciar puntuaciÃ³n",
        HAND_PREVIEW    = "Anunciar la mano al seleccionar",
        SCORING_DETAIL  = "Detalle de puntuaciÃ³n",
        DETAIL_FULL     = "Completo",
        DETAIL_JOKERS   = "Solo comodines",
        DETAIL_SUMMARY  = "Resumen",
        ROUND_ACTIONS   = "Anunciar jugadas y descartes",
        KEYBINDS        = "Controles",
        ANNOUNCEMENTS   = "Anuncios",
        TUTORIAL        = "Jugar tutorial",
        UNAVAILABLE     = "Ajustes de Blindfold no disponibles",
        PRESS_KEY       = "Presiona una tecla o botÃ³n de mando para {action}",
        BOUND           = "{action} asignado a {key}",
        CANCELLED       = "ReasignaciÃ³n cancelada",
        ANN_TYPE        = "Anunciar tipo",
        ANN_SUBTYPE     = "Anunciar rareza",
        ANN_SELECTED    = "Anunciar selecciÃ³n",
        ANN_DESCRIPTION = "Anunciar descripciones",
        ANN_TOOLTIP     = "Anunciar informaciÃ³n emergente",
        ANN_EXTRAS      = "Anunciar informaciÃ³n de opciones",
        ANN_POSITION    = "Anunciar posiciÃ³n",
        ANN_CONTAINER   = "Anunciar zona",
        ANN_SCREEN      = "Anunciar cambios de pantalla",
    },
}
